TYPO3:
  Imagine:
    driver: 'Gd'
    profile:
      'RGB': 'color.org/sRGB_IEC61966-2-1_black_scaled.icc'
      'CMYK': 'Adobe/CMYK/USWebUncoated.icc'
      'Grayscale': 'colormanagement.org/ISOcoated_v2_grey1c_bas.ICC'
  Flow:
    object:
      excludeClasses:
       'imagine.imagine': ['Imagine\\Test\\.*']